// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactHooksTemplate = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, { }), "index1");

/*  Not a pure module */
